// Products
export const GET_ALL_PRODUCTS = 'GET ALL PRODUCTS';
export const GET_PRODUCTS_PER_DAY = 'GET PRODUCTS PER DAY';
export const SHOW_MODAL_PRODUCTS = 'SHOW MODAL PRODUCTS';
export const CLOSE_MODAL_PRODUCTS = 'CLOSE MODAL PRODUCTS';
export const TOOGLE_FETCH_PROD_BY_DAY_LOADER = 'TOOGLE FETCH LOADER';
export const FETCH_ERROR = 'FETCH ERROR';
export const ADD_PRODUCT_BY_DAY = 'ADD PRODUCT BY DAY';
