// Products
export const GET_ALL_PRODUCTS = 'GET ALL PRODUCTS';
export const GET_PRODUCTS_PER_DAY = 'GET PRODUCTS PER DAY';
export const TOOGLE_MODAL_PRODUCTS = 'TOOGLE MODAL PRODUCTS';
export const TOOGLE_FETCH_LOADER = 'TOOGLE FETCH LOADER';
